import type { Answers } from "@/lib/analysis";
import type { Verdict } from "@/lib/recommendation-engine";

export type RecommendationScenario = {
  acceptableAlternates?: Verdict[];
  answers: Answers;
  category: string;
  dealQuality: number;
  explanation: string;
  expectedScoreRanges: {
    dealQuality: [number, number];
    impulseRisk: [number, number];
    practicalValue: [number, number];
    regretRisk: [number, number];
  };
  expectedVerdict: Verdict;
  id: string;
  productName: string;
  productUrl?: string;
};

export const recommendationScenarios: RecommendationScenario[] = [
  {
    id: "kindle-daily-reader",
    productName: "Kindle Paperwhite",
    category: "Reading device",
    answers: { similar: "No", wantedFor: "More than a month", usage: "Daily" },
    expectedVerdict: "BUY",
    dealQuality: 50,
    expectedScoreRanges: {
      dealQuality: [40, 60],
      impulseRisk: [10, 45],
      practicalValue: [75, 100],
      regretRisk: [10, 45],
    },
    explanation: "Frequent use and long-term desire make this a strong practical buy.",
  },
  {
    id: "viral-mini-gadget",
    productName: "Viral mini desk gadget",
    category: "Viral gadget",
    answers: { similar: "No", wantedFor: "Just today", usage: "Rarely" },
    expectedVerdict: "SKIP",
    dealQuality: 35,
    expectedScoreRanges: {
      dealQuality: [20, 45],
      impulseRisk: [65, 100],
      practicalValue: [0, 35],
      regretRisk: [65, 100],
    },
    explanation: "Trend appeal and low use should not survive the initial excitement.",
  },
  {
    id: "hair-dryer-upgrade",
    productName: "Quiet ionic hair dryer upgrade",
    category: "Hair tool",
    answers: { similar: "Yes, but I want an upgrade", wantedFor: "More than a month", usage: "Daily" },
    expectedVerdict: "BUY",
    acceptableAlternates: ["WAIT"],
    dealQuality: 55,
    expectedScoreRanges: {
      dealQuality: [40, 65],
      impulseRisk: [15, 45],
      practicalValue: [68, 100],
      regretRisk: [15, 50],
    },
    explanation: "Daily use plus a meaningful performance upgrade can justify buying.",
  },
  {
    id: "decorative-vase",
    productName: "Decorative ceramic vase",
    category: "Home decor",
    answers: { similar: "Yes", wantedFor: "Just today", usage: "Rarely" },
    expectedVerdict: "SKIP",
    dealQuality: 40,
    expectedScoreRanges: {
      dealQuality: [25, 50],
      impulseRisk: [65, 95],
      practicalValue: [0, 35],
      regretRisk: [70, 100],
    },
    explanation: "Duplicate decor with rare use should lean clearly skip.",
  },
  {
    id: "laptop-upgrade",
    productName: "Laptop with faster performance and longer battery life",
    category: "Electronics",
    answers: { similar: "Yes, but I want an upgrade", wantedFor: "More than a month", usage: "Daily" },
    expectedVerdict: "BUY",
    acceptableAlternates: ["WAIT"],
    dealQuality: 45,
    expectedScoreRanges: {
      dealQuality: [35, 60],
      impulseRisk: [15, 45],
      practicalValue: [70, 100],
      regretRisk: [20, 55],
    },
    explanation: "Meaningful daily-use upgrades should not be treated like novelty duplication.",
  },
  {
    id: "air-fryer",
    productName: "Air fryer",
    category: "Kitchen appliance",
    answers: { similar: "No", wantedFor: "Just today", usage: "Monthly" },
    expectedVerdict: "WAIT",
    dealQuality: 50,
    expectedScoreRanges: {
      dealQuality: [35, 60],
      impulseRisk: [45, 75],
      practicalValue: [35, 65],
      regretRisk: [35, 70],
    },
    explanation: "Could be useful, but monthly-use optimism should not auto-convert to buy.",
  },
  {
    id: "running-shoes-upgrade",
    productName: "Running shoes for an existing runner",
    category: "Fitness shoes",
    answers: { similar: "Yes, but I want an upgrade", wantedFor: "About a week", usage: "Weekly" },
    expectedVerdict: "BUY",
    acceptableAlternates: ["WAIT"],
    dealQuality: 50,
    expectedScoreRanges: {
      dealQuality: [40, 60],
      impulseRisk: [20, 55],
      practicalValue: [65, 95],
      regretRisk: [20, 55],
    },
    explanation: "A real weekly habit should be treated differently from an imagined one.",
  },
  {
    id: "expensive-fitness-gadget",
    productName: "Expensive smart fitness gadget",
    category: "Fitness gadget",
    answers: { similar: "No", wantedFor: "Just today", usage: "Daily" },
    expectedVerdict: "WAIT",
    dealQuality: 45,
    expectedScoreRanges: {
      dealQuality: [35, 55],
      impulseRisk: [45, 80],
      practicalValue: [40, 70],
      regretRisk: [45, 80],
    },
    explanation: "Claimed daily use should not automatically beat aspirational-habit risk.",
  },
  {
    id: "skincare-refill",
    productName: "Refill of a daily skincare staple",
    category: "Skincare refill",
    answers: { similar: "Yes", wantedFor: "About a week", usage: "Daily" },
    expectedVerdict: "BUY",
    dealQuality: 45,
    expectedScoreRanges: {
      dealQuality: [35, 60],
      impulseRisk: [10, 40],
      practicalValue: [70, 100],
      regretRisk: [10, 45],
    },
    explanation: "Replenishment should not be penalized as unnecessary duplication.",
  },
  {
    id: "trendy-dress",
    productName: "Trendy dress",
    category: "Fashion",
    answers: { similar: "Yes", wantedFor: "Just today", usage: "Rarely" },
    expectedVerdict: "SKIP",
    dealQuality: 45,
    expectedScoreRanges: {
      dealQuality: [35, 55],
      impulseRisk: [60, 95],
      practicalValue: [0, 40],
      regretRisk: [65, 100],
    },
    explanation: "Trend-driven, duplicate, and rare-use fashion should lean skip.",
  },
  {
    id: "desk-chair-upgrade",
    productName: "Ergonomic desk chair replacing an uncomfortable one",
    category: "Work setup",
    answers: { similar: "Yes, but I want an upgrade", wantedFor: "More than a month", usage: "Daily" },
    expectedVerdict: "BUY",
    dealQuality: 45,
    expectedScoreRanges: {
      dealQuality: [35, 55],
      impulseRisk: [10, 35],
      practicalValue: [75, 100],
      regretRisk: [10, 40],
    },
    explanation: "A daily friction-reducer should be treated as strongly practical.",
  },
  {
    id: "deep-sale-low-use",
    productName: "50% off novelty sale item",
    category: "Sale gadget",
    answers: { similar: "Yes", wantedFor: "Just today", usage: "Rarely" },
    expectedVerdict: "SKIP",
    dealQuality: 85,
    expectedScoreRanges: {
      dealQuality: [75, 95],
      impulseRisk: [60, 95],
      practicalValue: [0, 35],
      regretRisk: [65, 100],
    },
    explanation: "A huge discount should not rescue low-value duplication.",
  },
  {
    id: "coffee-grinder",
    productName: "Coffee grinder",
    category: "Kitchen appliance",
    answers: { similar: "No", wantedFor: "About a week", usage: "Weekly" },
    expectedVerdict: "BUY",
    acceptableAlternates: ["WAIT"],
    dealQuality: 50,
    expectedScoreRanges: {
      dealQuality: [40, 60],
      impulseRisk: [20, 50],
      practicalValue: [60, 90],
      regretRisk: [20, 55],
    },
    explanation: "Weekly repeated use can justify kitchen tools when the routine already exists.",
  },
  {
    id: "statement-handbag",
    productName: "Statement handbag",
    category: "Fashion accessory",
    answers: { similar: "Yes, but I want an upgrade", wantedFor: "Just today", usage: "Rarely" },
    expectedVerdict: "SKIP",
    acceptableAlternates: ["WAIT"],
    dealQuality: 40,
    expectedScoreRanges: {
      dealQuality: [30, 50],
      impulseRisk: [60, 95],
      practicalValue: [0, 45],
      regretRisk: [60, 100],
    },
    explanation: "Cosmetic upgrades with rare use should not slip through as balanced waits.",
  },
  {
    id: "suitcase-trip",
    productName: "Carry-on suitcase for an upcoming trip",
    category: "Travel gear",
    answers: { similar: "No", wantedFor: "About a week", usage: "Monthly" },
    expectedVerdict: "WAIT",
    acceptableAlternates: ["BUY"],
    dealQuality: 50,
    expectedScoreRanges: {
      dealQuality: [40, 60],
      impulseRisk: [20, 50],
      practicalValue: [45, 80],
      regretRisk: [20, 55],
    },
    explanation: "A concrete use case helps, but the routine is still intermittent.",
  },
  {
    id: "wall-art",
    productName: "Large wall art print",
    category: "Home decor",
    answers: { similar: "No", wantedFor: "More than a month", usage: "Monthly" },
    expectedVerdict: "WAIT",
    acceptableAlternates: ["BUY"],
    dealQuality: 45,
    expectedScoreRanges: {
      dealQuality: [35, 55],
      impulseRisk: [20, 50],
      practicalValue: [35, 70],
      regretRisk: [25, 60],
    },
    explanation: "Long-term desire can make decor reasonable without making it an automatic buy.",
  },
  {
    id: "planner",
    productName: "Work planner",
    category: "Study and work tool",
    answers: { similar: "No", wantedFor: "About a week", usage: "Daily" },
    expectedVerdict: "BUY",
    dealQuality: 40,
    expectedScoreRanges: {
      dealQuality: [30, 50],
      impulseRisk: [15, 40],
      practicalValue: [70, 100],
      regretRisk: [10, 40],
    },
    explanation: "Support for a current daily routine should read as practical, not overcautious.",
  },
  {
    id: "espresso-machine",
    productName: "Home espresso machine",
    category: "Kitchen appliance",
    answers: { similar: "No", wantedFor: "More than a month", usage: "Weekly" },
    expectedVerdict: "BUY",
    acceptableAlternates: ["WAIT"],
    dealQuality: 55,
    expectedScoreRanges: {
      dealQuality: [45, 70],
      impulseRisk: [15, 45],
      practicalValue: [60, 90],
      regretRisk: [20, 55],
    },
    explanation: "A repeated habit and long interest can justify a more discretionary tool.",
  },
  {
    id: "walking-pad",
    productName: "Walking pad",
    category: "Fitness equipment",
    answers: { similar: "No", wantedFor: "Just today", usage: "Daily" },
    expectedVerdict: "WAIT",
    acceptableAlternates: ["SKIP"],
    dealQuality: 50,
    expectedScoreRanges: {
      dealQuality: [40, 60],
      impulseRisk: [45, 80],
      practicalValue: [35, 70],
      regretRisk: [40, 80],
    },
    explanation: "This is exactly the sort of aspirational-habit purchase that should trigger caution.",
  },
  {
    id: "gaming-headset",
    productName: "Gaming headset",
    category: "Electronics",
    answers: { similar: "No", wantedFor: "About a week", usage: "Weekly" },
    expectedVerdict: "BUY",
    acceptableAlternates: ["WAIT"],
    dealQuality: 50,
    expectedScoreRanges: {
      dealQuality: [40, 60],
      impulseRisk: [20, 50],
      practicalValue: [60, 90],
      regretRisk: [20, 55],
    },
    explanation: "A weekly existing habit should not be flattened into WAIT by default.",
  },
  {
    id: "extra-serum",
    productName: "Another trendy serum",
    category: "Beauty",
    answers: { similar: "Yes", wantedFor: "Just today", usage: "Rarely" },
    expectedVerdict: "SKIP",
    dealQuality: 45,
    expectedScoreRanges: {
      dealQuality: [35, 55],
      impulseRisk: [60, 95],
      practicalValue: [0, 40],
      regretRisk: [65, 100],
    },
    explanation: "Owning similar products plus rare use should raise regret sharply.",
  },
  {
    id: "meal-prep-containers",
    productName: "Meal prep container set",
    category: "Kitchen / organization",
    answers: { similar: "No", wantedFor: "About a week", usage: "Weekly" },
    expectedVerdict: "BUY",
    acceptableAlternates: ["WAIT"],
    dealQuality: 45,
    expectedScoreRanges: {
      dealQuality: [35, 55],
      impulseRisk: [20, 50],
      practicalValue: [60, 90],
      regretRisk: [20, 50],
    },
    explanation: "Simple tools that support an existing weekly routine can still be practical buys.",
  },
  {
    id: "scrapbook-supplies",
    productName: "Scrapbook supplies bundle",
    category: "Hobby",
    answers: { similar: "Yes", wantedFor: "Just today", usage: "Rarely" },
    expectedVerdict: "SKIP",
    acceptableAlternates: ["WAIT"],
    dealQuality: 55,
    expectedScoreRanges: {
      dealQuality: [45, 65],
      impulseRisk: [55, 90],
      practicalValue: [0, 45],
      regretRisk: [60, 95],
    },
    explanation: "Hobby duplication with rare use should not hide inside the WAIT bucket.",
  },
  {
    id: "noise-canceling-headphones",
    productName: "Noise-canceling headphones upgrade",
    category: "Electronics",
    answers: { similar: "Yes, but I want an upgrade", wantedFor: "More than a month", usage: "Daily" },
    expectedVerdict: "BUY",
    acceptableAlternates: ["WAIT"],
    dealQuality: 55,
    expectedScoreRanges: {
      dealQuality: [45, 70],
      impulseRisk: [10, 40],
      practicalValue: [72, 100],
      regretRisk: [15, 50],
    },
    explanation: "Daily experience improvements should get strong positive weight.",
  },
  {
    id: "phone-color-upgrade",
    productName: "New phone in a trendier color",
    category: "Electronics",
    answers: { similar: "Yes, but I want an upgrade", wantedFor: "Just today", usage: "Daily" },
    expectedVerdict: "WAIT",
    acceptableAlternates: ["SKIP"],
    dealQuality: 45,
    expectedScoreRanges: {
      dealQuality: [35, 55],
      impulseRisk: [45, 80],
      practicalValue: [35, 70],
      regretRisk: [45, 85],
    },
    explanation: "Daily use alone should not overpower a mostly cosmetic upgrade.",
  },
  {
    id: "replacement-water-bottle",
    productName: "Replacement insulated water bottle",
    category: "Daily-use accessory",
    answers: { similar: "Yes, but I want an upgrade", wantedFor: "About a week", usage: "Daily" },
    expectedVerdict: "BUY",
    acceptableAlternates: ["WAIT"],
    dealQuality: 45,
    expectedScoreRanges: {
      dealQuality: [35, 55],
      impulseRisk: [15, 45],
      practicalValue: [65, 90],
      regretRisk: [15, 50],
    },
    explanation: "A small but frequent-use replacement can be a sensible buy.",
  },
];
